# Generated by Django 2.0 on 2019-07-05 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='post',
            new_name='opinion',
        ),
    ]
